travis:
  secure:
    BINSTAR_TOKEN: KTULK0FWEOMOQTJyzFcbpF0wp411oe948lK1KAq4cE9QV350l9iyxB2YMUb4j9FLcTbXtctBWdol6g2iG9xrbPrMT/56/3V7VVWNyeM/HBpG/4IqJZOEdxycHbQ58v6Qb+2lpuVmu4I8UpsqKFxeBhTa2+NagiLk/pFk3sH8EzJwzgtr13zkERdm6j5YzYfI23O8t2JCFqwTxPNWrWC5ICzA879IUZ0HvQdrepkvX7lhKmTzD+7N2WcX9sLYBkp5cuvgX4GtFFe2ACnjc8MRSA7905sxCEruOA6fgP+Q0o5WkwWTyF9d/JhSbGnoCfP6O+cvt+ux1SkYmYD50iqcPKOK05RKBW56j7mkNXMBcV2HeS497ZAf8ENaF2FDvuzyetlsE/igOcGB5L3CKnVJB+KVLKcDvBLlOe/qEaQ+NlPLgy2DgAf6xN0Ev/mMdAu6FoGe67W5Vk1xYiPL9lZu7hNGqScxrEfwngZUf4MERCvIrDABdFJaVWk11+zAZ5X0s8rQViuz96r6XzW5nXk7e5H6Vjv5jb5lmSCWrTUMgX8qYkputUkR9hFy6vyn+MLyhO5LmZ7rHVxhfrD9kbmguRy7Bw7+vJnBH6wIcxtdcqcEVkt7e9G0Le8rVaZ24DLXwF3NpFFfN6UsbXjCxnunbAECk4QycIm2kIkf/5Ut9hQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
