travis:
  secure:
    BINSTAR_TOKEN: RQH5fT5FM0Pf74//tyirJzMnQST4wdloOJUkRZrw79TNOCjZt0l85oC1wxfyECYs0V8cLBd8wjK9wo1bW6LDWDhrL9daQeHLJ3/GiOcaN0FjvcPUP55MuzJtky/RAZJUMYv/9iy9N4u3mZYhVBgUHDZVQeGYhimv+pYvYDXPBglrNq4RPdpo7dy9NZf2QNCZJWwDfVW/zKo+kompfI2PzOqin+7OtAlmYP5aciXKgp7CIN9Xs/lIl8ayR9lu+r+C+SbCf3kzEQS815vSgu2gdSZiAHQhR56c1my3L6RKl+LJ/GVu49Ex8jcHPOQf1IfOqmG54J35WDwQ/iHlBoEDse4jGR/TGGV8yK2GiouCVrjZTZBnHjHqbdb4aft1qQugP+7dcnyAdgSgiinHMvKy/8zwmpPCxft47NXEaRiQDsVs1H04FYQyoG9MwoyDYz0gQs0Gn0nJATKC1xQbdFtHii82/YJ4pZlezLzzb9D3mpI1jKq0FFB1lVejJjrV7MOAdOyBJVGt7ZimmuSzTef9AqTMQQWPIUUkwpg58NXytFNmJJ/iGHhEirY0XHJ+VGDXiaDN9keTnag/N39au3VgOOdrzvwyt2TQBDbSB8sqZMlj3bjISIKz3Dv/abs+CLYvcvOy68GoQGYmoVAemAEuXP0SrQt4T+Ba7ZhkTHQahEw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
